version: '3.8'
services:
  nodeJs:
    image: node:latest
    container_name: nodeJs
    restart: always
    env_file:
      - .env
    ports: ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: yarn start
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-files: '5'

  db-mongo:
    image: mongo
    container_name: mongoDB
    restart: always
    depends_on:
      - nodeJS
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
