export const header = [
  { id: 'id', title: 'ID' },
  { id: 'code', title: 'Código' },
  { id: 'name', title: 'Nome' },
  { id: 'unit', title: 'Unidade' },
  { id: 'ncm', title: 'NCM' },
  { id: 'origin', title: 'Origem' },
  { id: 'price', title: 'Preço' },
  { id: 'fixed_ipi_value', title: 'Valor IPI fixo' },
  { id: 'comments', title: 'Observações' },
  { id: 'situation', title: 'Situação' },
  { id: 'inventory', title: 'Estoque' },
  { id: 'cost_price', title: 'Preço de custo' },
  { id: 'code_in_the_supplier', title: 'Cód no fornecedor' },
  { id: 'provider', title: 'Fornecedor' },
  { id: 'location', title: 'Localização' },
  { id: 'maximum_stock', title: 'Estoque maximo' },
  { id: 'minimum_stock', title: 'Estoque minimo' },
  { id: 'liquid_weight_kg', title: 'Peso líquido (Kg)' },
  { id: 'gross_weight_kg', title: 'Peso bruto (Kg)' },
  { id: 'gtin_ean', title: 'GTIN/EAN' },
  { id: 'gtin_ean_packing', title: 'GTIN/EAN da embalagem' },
  { id: 'product_width', title: 'Largura do Produto' },
  { id: 'product_height', title: 'Altura do Produto' },
  { id: 'product_depth', title: 'Profundidade do produto' },
  { id: 'expiration_date', title: 'Data Validade' },
  {
    id: 'product_description_in_supplier',
    title: 'Descrição do Produto no Fornecedor',
  },
  { id: 'complementary_description', title: 'Descrição Complementar' },
  { id: 'cashier_unit', title: 'Unidade por Caixa' },
  { id: 'product_variation', title: 'Produto Variação' },
  { id: 'production_type', title: 'Tipo Produção' },
  {
    id: 'ipi_framework_class',
    title: 'Classe de enquadramento do IPI',
  },
  {
    id: 'service_list_code',
    title: 'Código da lista de serviços',
  },
  { id: 'item_type', title: 'Tipo do item' },
  { id: 'tags_group', title: 'Grupo de Tags/Tags' },
  { id: 'tax', title: 'Tributos' },
  { id: 'father_code', title: 'Código Pai' },
  { id: 'integration_code', title: 'Código Integração' },
  { id: 'product_group', title: 'Grupo de produtos' },
  { id: 'brand', title: 'Marca' },
  { id: 'cest', title: 'CEST' },
  { id: 'volumes', title: 'Volumes' },
  { id: 'short_description', title: 'Descrição Curta' },
  { id: 'cross_docking', title: 'Cross-Docking' },
  { id: 'url_external_images', title: 'URL Imagens Externas' },
  { id: 'external_link', title: 'Link Externo' },
  {
    id: 'months_warranty_in_the_supplier',
    title: 'Meses Garantia no Fornecedor',
  },
  { id: 'product_condition', title: 'Condição do produto' },
  { id: 'free_shipping', title: 'Frete Grátis' },
  { id: 'fci_number', title: 'Número FCI' },
  { id: 'video', title: 'Vídeo' },
  { id: 'department', title: 'Departamento' },
  { id: 'unit_of_measurement', title: 'Unidade de medida' },
  { id: 'purchase_price', title: 'Preço de compra' },
  {
    id: 'icms_st_base_value_for_retention',
    title: 'Valor base ICMS ST para retenção',
  },
  {
    id: 'icms_st_value_for_retention',
    title: 'Valor_ICMS_ST_para_retenção',
  },
  {
    id: 'substitutes_own_icms_value',
    title: 'Valor ICMS próprio do substituto',
  },
  { id: 'product_category', title: 'Categoria do produto' },
];
